import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import Highcharts from 'highcharts';
import HighchartsReact from 'highcharts-react-official';
import styles from '@/styles/Home.module.css'
import Card from '@/components/Card'

import axios from 'axios';
import { FormEvent, useState, useEffect } from 'react'

export default function Home() {


  const [assets, setAssets] = useState<any[]>([])

  useEffect(() => {
    axios.get("https://my-json-server.typicode.com/tractian/fake-api/assets")
    .then((response) => {
      console.log(response.data)
      setAssets(response.data)
    })
    .catch(() => {
      console.log("Algo deu errado")
    })
  },[])

  const options1 = {
    chart: {
      type: 'spline',
      borderRadius: 10,
      height: (9 / 16 * 100) + '%',
    },
    title: {
      text: 'Temperatura Máxima [ºC]'
    },
    series: [
      {
        data: [1,4,2,5,3,8]
      }
    ]
  };

  const options2 = {
    chart: {
      type: 'bar',
      borderRadius: 10,
      height: (9 / 16 * 100) + '%',
    },
    title: {
      text: 'Saúde [%]'
    },
    series: [
      {
        data: [8,4,2,5,3,1]
      }
    ]
  };

  return (
    <>
      <Head>
        <title>Monitoramento</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>

        <div className={styles.title}>
          <Link
            href="https://tractian.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              src="/logo.png"
              alt="Logo"
              width={200}
              height={30}
              priority
            />
          </Link>
        </div>
        
        <div className={styles.graph}>

          <HighchartsReact highcharts={Highcharts} options={options1} />
          <HighchartsReact highcharts={Highcharts} options={options2} />

        </div>

        <div className={styles.grid}>
          <Card title="Ativos" description="Monitore informações dos ativos em tempo real." path="asset"></Card>
          <Card title="Unidades" description="Veja as empresas e suas respectivas unidades." path="companies"></Card>
          <Card title="Atividades" description="Confira ordens de trabalho, seus status e asignees." path="workorders"></Card>
          <Card title="Colaboradores" description="Veja os usuários do sistema." path="users"></Card>
        </div>

      </main>
    </>
  )
}
