import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import Highcharts from 'highcharts';
import HighchartsReact from 'highcharts-react-official';
import styles from '@/styles/Home.module.css'
import axios from 'axios';

import { Card } from '../components/Card'
import { useState, useEffect } from 'react'

export default function Home() {

  const [assets, setAssets] = useState<any[]>([])

  useEffect(() => {
    axios.get("https://my-json-server.typicode.com/tractian/fake-api/assets")
    .then((response) => {
      console.log(response.data[1].specifications.maxTemp)
      setAssets(response.data)
    })
    .catch(() => {
      console.log("Algo deu errado")
    })
  },[])

  let options1 = {}
  let options2 = {}

  return (
    <>
      <Head>
        <title>Monitoramento</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.home}>

        <div className={styles.title}>
          <Link
            href="https://tractian.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              src="/logo.png"
              alt="Logo"
              width={200}
              height={30}
              priority
            />
          </Link>
        </div>
        
        <div className={styles.graph}>
          {assets.map((asset, key) => {

            options1 = {
              chart: {
                type: 'spline',
                borderRadius: 10,
                height: (9 / 16 * 100) + '%',
              },
              colors: ['orange'],
              title: {
                text: 'Temperatura Máxima [°C] nos ativos'
              },
              xAxis: {
                categories: [
                              assets[0].name, 
                              assets[1].name,
                              assets[2].name,
                              assets[3].name,
                              assets[4].name,
                              assets[5].name
                            ]
              },
              series: [
                {
                  name: 'Temperatura',

                  data: [
                          assets[0].specifications.maxTemp, 
                          assets[1].specifications.maxTemp, 
                          assets[2].specifications.maxTemp,
                          assets[3].specifications.maxTemp,
                          assets[4].specifications.maxTemp,
                          assets[5].specifications.maxTemp
                        ]
                }
              ]
            };

            options2 = {
              chart: {
                type: 'bar',
                borderRadius: 10,
                height: (9 / 16 * 100) + '%',
              },
              colors: ['#22c55e'],
              title: {
                text: 'Saúde dos ativos em [%]'
              },
              xAxis: {
                categories: [
                              assets[0].name, 
                              assets[1].name,
                              assets[2].name,
                              assets[3].name,
                              assets[4].name,
                              assets[5].name
                            ]
              },
              series: [
                {
                  name: "Saúde [%]",
                  data: [
                          assets[0].healthscore, 
                          assets[1].healthscore, 
                          assets[2].healthscore,
                          assets[3].healthscore,
                          assets[4].healthscore,
                          assets[5].healthscore
                        ]
                },
              ]
            };

            return(
              <div className={styles.code} key={key}>

              </div>
            )

          })}

          <HighchartsReact highcharts={Highcharts} options={options1} />
          <HighchartsReact highcharts={Highcharts} options={options2} />

        </div>

        <div className={styles.grid}>
          <Card title="Ativos" description="Monitore informações dos ativos em tempo real." path="asset"></Card>
          <Card title="Unidades" description="Veja as empresas e suas respectivas unidades." path="companies"></Card>
          <Card title="Atividades" description="Confira ordens de trabalho, seus status e asignees." path="workorders"></Card>
          <Card title="Colaboradores" description="Veja os usuários do sistema." path="users"></Card>
        </div>

      </main>
    </>
  )
}
