import Head from 'next/head'
import Image from 'rc-image';
import { toast } from 'react-toastify';

import { useState } from 'react'
import styles from '@/styles/Home.module.css'

import { Sidebar } from '@/components/Sidebar';

import ClientAssets from '@/services/assets';

export default function Assets() {

  const [assets, setAssets] = useState<any[]>([])
  const [id, setId] = useState<any>();

  async function handleFilter(e:any) {
    e.preventDefault();
    const response:any = await ClientAssets.listAssetById(id);
    if (response.status === 200) {
        toast.success('Sucesso!');
        setAssets(response.data);
    } else {
        toast.error('Ops algo deu errado!');
    }
  }

  return (
    <>
      <Sidebar 
        path1="users" path2="companies" path3="workorders"
        name1='Colaboradores' name2='Unidades' name3='Atividades'
      />
      <Head>
        <title>Ativos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>

        <div>
          <h1 className={styles.title}>Ativos</h1>
        </div>

        <div>
          <div className={styles.form}>
                      
            <form className="form-profile" onSubmit={handleFilter}>

              <label className={styles.label}>Selecione o Id do ativo
                <select className={styles.filter} name="id" id="id" value={id} onChange={(e) => setId(e.target.value)}>
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                  <option value="5">5</option>
                  <option value="6">6</option>
                  <option value="all" selected>All</option>
                </select>
              </label>
              <input className={styles.submit} type="submit" value="Consultar"></input>
              <a className={styles.submit} type="submit" href='charts'>Gráficos</a>

            </form>
          </div>
        </div>
        <br></br>

        <div className={styles.code}>
          {assets.map((asset, key) => {

            let unit_name = ''
            asset.unitId === 1 ? unit_name = 'Jaguar Unit' : unit_name = 'Tobias Unit'

            let date = asset.metrics.lastUptimeAt.split("T",1)
            let time = asset.metrics.lastUptimeAt.slice(11,-5)
            let lastUptime = date.concat(" às ", time)

            let status = ''
            switch(asset.status){
              case "inAlert":
                status = 'EM ALERTA!';
                break;
              case "inOperation":
                status = 'Em Operação';
                break;
              case "inDowntime":
                status = 'Em Parada';
                break;
            }

            return (
              <div className={styles.card} key={key}>

                <span className="">Nome: {asset.name}</span><br></br>
                <span className="">Modelo: {asset.model}</span><br></br>
                <span className="">Unidade: {unit_name}</span><br></br>
                <span className="">Status: {status}</span><br></br>
                <span className="">Total de coletas: {asset.metrics.totalCollectsUptime}</span><br></br>
                <span className="">Horas coletadas: {asset.metrics.totalUptime}</span><br></br>
                <span className="">Última coleta: {lastUptime}</span>

                <div className={styles.img}>
                  <Image
                    src={asset.image}
                    alt="Ativo"
                    width='50%'
                    height='50%'
                  />
                </div>

              </div>
            )

          })}
        </div>

      </main>
    </>
  )
}
