import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import axios from 'axios';
import { FormEvent, useState, useEffect } from 'react'
import styles from '@/styles/Home.module.css'


export default function Assets() {

  let id = 4
  const [assets, setAssets] = useState<any[]>([])

  useEffect(() => {
    axios.get("https://my-json-server.typicode.com/tractian/fake-api/assets", {
      params: {
        id: id
      }
    })
    .then((response) => {
      console.log(response.data)
      setAssets(response.data)
    })
    .catch(() => {
      console.log("Algo deu errado")
    })
  })


  return (
    <>
      <Head>
        <title>Assets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>

          <div>
            <Link
              href="/"
            >
              By{' '}
              <Image
                src="/logo.png"
                alt="Vercel Logo"
                width={100}
                height={100}
                priority
              />
            </Link>
          </div>

          <div>
            {assets.map((asset, key) => {

            return(
              <div key={key}>
                <span className="">Nome: {asset.name}</span><br></br>
                <span className="">Modelo: {asset.model}</span><br></br>
                <span className="">Status: {asset.status}</span>
              </div>
            )

            })}
          </div>

        </div>
      </main>
    </>
  )
}
