import Head from 'next/head'

import axios from 'axios';
import { useState, useEffect } from 'react'
import styles from '@/styles/Home.module.css'

import Card from '@/components/Card';
import Sidebar from '@/components/Sidebar';

export default function Companies() {

  const [companies, setCompanies] = useState<any[]>([])

  useEffect(() => {
    axios.get("https://my-json-server.typicode.com/tractian/fake-api/units")
    .then((response) => {
      console.log(response.data)
      setCompanies(response.data)
    })
    .catch(() => {
      console.log("Algo deu errado")
    })
  },[])


  return (
    <>
      <Sidebar 
        path1="asset" path2="users" path3="workorders"
        name1='Ativos' name2='Colaboradores' name3='Atividades'
      />
      <Head>
        <title>Unidades</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>

        <div>
          <h1 className={styles.title}>Unidades</h1>
        </div>

        <div className={styles.buttons}>
          <button className={styles.edit}>Editar</button>
          <button className={styles.add}>Nova Unidade</button>
          <button className={styles.delete}>Excluir</button>
        </div>

        <div className={styles.companies}>
          {companies.map((unit, key) => {

            let company_name = ''
            unit.companyId === 1 ? company_name = 'The Test Company' : company_name = 'Não encontrado'
            let str1 = "Empresa: "
            company_name = str1.concat(company_name)

            return(
              <div className={styles.unit} key={key}>
                <Card title={unit.name} description={company_name} path="https://tractian.com/"></Card>
              </div>
            )

          })}
        </div>

      </main>
    </>
  )
}
