import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import axios from 'axios';
import { FormEvent, useState, useEffect } from 'react'
import styles from '@/styles/Home.module.css'

import Card from '@/components/Card';


export default function Assets() {

  const [assets, setAssets] = useState<any[]>([])

  useEffect(() => {
    axios.get("https://my-json-server.typicode.com/tractian/fake-api/units")
    .then((response) => {
      console.log(response.data)
      setAssets(response.data)
    })
    .catch(() => {
      console.log("Algo deu errado")
    })
  },[])


  return (
    <>
      <Head>
        <title>Unidades</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>

        <div className={styles.title}>
          <Link
            href="/"
          >
            <Image
              src="/logo.png"
              alt="Logo"
              width={200}
              height={30}
              priority
            />
          </Link>
        </div>

        <div>
          {assets.map((unit, key) => {

            let company_name = ''
            unit.companyId === 1 ? company_name = 'The Test Company' : company_name = 'Não encontrado'
            let str1 = "Empresa: "
            company_name = str1.concat(company_name)

            return(
              <div className={styles.grid} key={key}>
                <Card title={unit.name} description={company_name} path="https://tractian.com/"></Card>
              </div>
            )

          })}
        </div>

      </main>
    </>
  )
}
