import Head from 'next/head'
import { FaTrash, FaEdit } from "react-icons/fa";

import axios from 'axios';
import { useState, useEffect } from 'react'
import styles from '@/styles/Home.module.css'

import { Sidebar } from '@/components/Sidebar';

export default function Workorders() {

  const [workorders, setWorkorders] = useState<any[]>([])

  useEffect(() => {
    axios.get("https://my-json-server.typicode.com/tractian/fake-api/workorders")
    .then((response) => {
      setWorkorders(response.data)
    })
    .catch(() => {
      console.log("Algo deu errado")
    })
  },[])


  return (
    <>
      <Sidebar 
        path1="asset" path2="companies" path3="users"
        name1='Ativos' name2='Unidades' name3='Colaboradores'
      />

      <Head>
        <title>Atividades</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>
        
        <div>
          <h1 className={styles.title}>Atividades</h1>
        </div>


        <div className={styles.code}>
          {workorders.map((workorder, key) => {

            let size = workorder.assignedUserIds.length
            let userIds = workorder.assignedUserIds.toString().split(',',size)

            let user_name = []

            for (let i=0; i < size; i++ ){
              switch(userIds[i]){
                case "1":
                  user_name.push('John Doe, ');
                  break;
                case "2":
                  user_name.push('Jane Doe, ');
                  break;
                case "3":
                  user_name.push('Bob Smith ');
                  break;
                case "4":
                  user_name.push('Sarah Johnson, ');
                  break;
                case "5":
                  user_name.push('Tim Brown');
                  break;
              }
            }

            return(
              <div className={styles.card} key={key}>
                <span className="">Task: {workorder.title}</span><br></br>
                <span className="">Descrição: {workorder.description}</span><br></br>
                <span className="">Ativo: {workorder.assetId}</span><br></br>
                <span className="">Assignees: {user_name}</span><br></br>
                <span className="">Status: {workorder.status}</span><br></br>
                <span className="">Prioridade: {workorder.priority}</span><br></br>
                <div className={styles.task_button}>
                  <button className={styles.edit}><a><FaEdit color="white" size={16} /> Editar</a></button>
                  <button className={styles.delete}><a><FaTrash color="white" size={16} /> Excluir</a></button>
                </div>
              </div>
            )

          })}
        </div>

      </main>
    </>
  )
}