import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import axios from 'axios';
import { FormEvent, useState, useEffect } from 'react'
import styles from '@/styles/Home.module.css'


export default function Assets() {

  let id = 1
  const [assets, setAssets] = useState<any[]>([])

  useEffect(() => {
    axios.get("https://my-json-server.typicode.com/tractian/fake-api/workorders", {
      params: {
        id: id
      }
    })
    .then((response) => {
      console.log(response.data)
      setAssets(response.data)
    })
    .catch(() => {
      console.log("Algo deu errado")
    })
  },[])


  return (
    <>
      <Head>
        <title>Atividades</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>
        
        <div className={styles.title}>
          <Link
            href="/"
          >
            <Image
              src="/logo.png"
              alt="Logo"
              width={200}
              height={30}
              priority
            />
          </Link>
        </div>


        <div className={styles.code}>
          {assets.map((workorder, key) => {

            return(
              <div key={key}>
                <span className="">Task: {workorder.title}</span><br></br>
                <span className="">Assignees: {workorder.assignedUserIds}</span><br></br>
                <span className="">Status: {workorder.status}</span><br></br>
                <span className="">Prioridade: {workorder.priority}</span><br></br>
              </div>
            )

          })}
        </div>

      </main>
    </>
  )
}