import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios';
import { FormEvent, useState, useEffect } from 'react'
import styles from '@/styles/Home.module.css'

export default function Users() {
  return (
    <>
      <Head>
        <title>Usuários</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>

          <div>
            <a
              href="/"
            >
              By{' '}
              <Image
                src="/logo.png"
                alt="Vercel Logo"
                width={100}
                height={100}
                priority
              />
            </a>
          </div>
        </div>

      </main>
    </>
  )
}
